name: Build Compatible EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.8 (32-bit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: 'x86'
      
      - name: Install PyInstaller
        run: python -m pip install pyinstaller
      
      - name: Check if file exists
        run: dir
      
      - name: Build EXE
        run: python -m PyInstaller --onefile --windowed --hidden-import tkinter --name "sadik" sadik.py
        
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: sadik-exe-final
          path: dist/sadik.exe
